### ISSUE TITLE
Use of unresolved identifier 'POPBasicAnimation'

### ISSUE THREAD

**Issue by ban9ban3** [ziyang0621/ZTDropDownTextField#1]
Can you help me? 
I just install pod and open it. but it show 6 error: in ZTDropDownTextField.swift 
- Use of unresolved identifier 'POPBasicAnimation'
- Use of unresolved identifier 'kPOPViewAlpha'
- Use of unresolved identifier 'POPBasicAnimation'
- Use of unresolved identifier 'kPOPLayoutConstraintConstant'
- Use of unresolved identifier 'POPSpringAnimation'
- Use of unresolved identifier 'kPOPViewSize'

**Comment by ziyang0621** [comment]
Hi @ban9ban3, 

ZTDropDownTextField uses Facebook pop as its dependency. So it is better to use it via cocoapods.

In your Podfile, you can just do the following:

use_frameworks!
pod 'ZTDropDownTextField'

**Comment by ban9ban3** [comment]
I did that but it still show that error:

This is my Podfile:

target 'ZTDropDownTextField' do

pod 'pop', '~> 1.0'
pod 'ZTDropDownTextField'

end

target 'ZTDropDownTextFieldTests' do

end

use_frameworks!

**Comment by ziyang0621** [comment]
I wonder why your target is `ZTDropDownTextField`? Did you download the project via the `Download Zip` button? If so, you should not need to change the `Podfile`.

**Comment by ban9ban3** [comment]
Thansk!! I redownload and install without add this line. It working. :+1:

**Comment by ziyang0621** [comment]
Nice! Grad you resolved it.
